### ISSUE TITLE
Error with cachedir flag

### ISSUE THREAD

**Issue by w3kim** [niwl/geph#1]
When I run geph in client mode with `--cachedir` I get this

```
iMac5k:test w3kim$ ./geph client --cachedir cache
2016/10/25 19:33:26 cache: cannot read sec.identity: sql: no rows in result set
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x452c800, 0xc420012110)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/bunsim/natrium%2ev1.ECDHPrivate.PublicKey(0x0, 0x0, 0x0, 0x450b8e0, 0xc4200ea780, 0xc4200132c0)
    /Users/w3kim/go/src/gopkg.in/bunsim/natrium.v1/diffie.go:32 +0xb9
github.com/bunsim/geph/client.(*Command).Execute(0xc42000a800, 0x4d76028, 0xc4200122a8, 0xc420072c60, 0x0, 0x0, 0x0, 0x1)
    /Users/w3kim/go/src/github.com/bunsim/geph/client/Command.go:131 +0x9b5
github.com/google/subcommands.(*Commander).Execute(0xc42005a070, 0x4d76028, 0xc4200122a8, 0x0, 0x0, 0x0, 0x4d76028)
    /Users/w3kim/go/src/github.com/google/subcommands/subcommands.go:142 +0x3a7
github.com/google/subcommands.Execute(0x4d76028, 0xc4200122a8, 0x0, 0x0, 0x0, 0xc4200e7f80)
    /Users/w3kim/go/src/github.com/google/subcommands/subcommands.go:372 +0x5f
main.main()
    /Users/w3kim/go/src/github.com/bunsim/geph/main.go:30 +0x27c
```

geph works fine without the flag. If I supply no arguments to the flag then geph properly shows `-cachedir` usage as expected. I suppose there's a bug while geph is generating a hash for caching.

**Comment by nullchinchilla** [comment]
The program attempted to use a null value for the private key to display a log message, even when there is no private key in the cache yet. Fixed in d3f7db82c6a0fb49c661dc6cc84868e1f11a29ae.
